const products = [
  {
    id: 1,
    name: "Premium Cotton Oversized Tee",
    price: 2499,
    originalPrice: 3499,
    category: "men",
    subCategory: "t-shirts",
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
    colors: ["#1a1a2e", "#ffffff", "#c9a96e", "#4a4a4a"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600",
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600"
    ],
    description: "Ultra-soft 100% premium cotton oversized tee. Perfect for everyday casual wear with a relaxed modern fit.",
    details: ["100% Premium Cotton", "Oversized Fit", "Ribbed crew neck", "Machine washable", "Available in 4 colors"],
    stock: 45,
    featured: true,
    newArrival: false,
  },
  {
    id: 2,
    name: "Slim Fit Chino Trousers",
    price: 3999,
    originalPrice: 5499,
    category: "men",
    subCategory: "trousers",
    rating: 4.6,
    reviews: 89,
    badge: "Sale",
    colors: ["#c9a96e", "#1a1a2e", "#6b6960"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600",
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600"
    ],
    description: "Modern slim fit chino trousers crafted from premium stretch fabric. Ideal for both office and casual outings.",
    details: ["98% Cotton 2% Elastane", "Slim Fit", "Four-pocket styling", "Belt loops", "Machine washable"],
    stock: 30,
    featured: true,
    newArrival: false,
  },
  {
    id: 3,
    name: "Floral Wrap Midi Dress",
    price: 4299,
    originalPrice: 5999,
    category: "women",
    subCategory: "dresses",
    rating: 4.9,
    reviews: 210,
    badge: "Top Rated",
    colors: ["#e8d5b0", "#c9a96e", "#1a1a2e"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600"
    ],
    description: "Elegant floral wrap midi dress with a flattering silhouette. Perfect for brunches, parties, and special occasions.",
    details: ["100% Viscose", "Wrap style", "Midi length", "Floral print", "Hand wash recommended"],
    stock: 18,
    featured: true,
    newArrival: true,
  },
  {
    id: 4,
    name: "Leather Crossbody Bag",
    price: 5499,
    originalPrice: 7999,
    category: "accessories",
    subCategory: "bags",
    rating: 4.7,
    reviews: 156,
    badge: "New",
    colors: ["#8B4513", "#1a1a2e", "#c9a96e"],
    sizes: ["One Size"],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600"
    ],
    description: "Premium genuine leather crossbody bag with adjustable strap and gold-tone hardware. Spacious yet compact design.",
    details: ["Genuine Leather", "Adjustable strap", "Gold-tone hardware", "Interior zip pocket", "Magnetic closure"],
    stock: 12,
    featured: true,
    newArrival: true,
  },
  {
    id: 5,
    name: "Knit Cardigan Sweater",
    price: 3799,
    originalPrice: 4999,
    category: "women",
    subCategory: "tops",
    rating: 4.5,
    reviews: 67,
    badge: "Sale",
    colors: ["#e8d5b0", "#ffffff", "#4a4a4a"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600",
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600"
    ],
    description: "Cozy ribbed knit cardigan with button-down front. A wardrobe essential for layering in style.",
    details: ["60% Cotton 40% Acrylic", "Button-down front", "Ribbed texture", "Relaxed fit", "Machine washable"],
    stock: 25,
    featured: false,
    newArrival: true,
  },
  {
    id: 6,
    name: "Classic White Sneakers",
    price: 4999,
    originalPrice: 6499,
    category: "footwear",
    subCategory: "sneakers",
    rating: 4.8,
    reviews: 302,
    badge: "Best Seller",
    colors: ["#ffffff", "#1a1a2e", "#c9a96e"],
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600"
    ],
    description: "Timeless classic white leather sneakers with cushioned sole. Goes with everything, lasts forever.",
    details: ["Genuine leather upper", "Rubber sole", "Cushioned insole", "Lace-up closure", "Wipe clean"],
    stock: 60,
    featured: true,
    newArrival: false,
  },
  {
    id: 7,
    name: "Linen Blazer",
    price: 6999,
    originalPrice: 9499,
    category: "men",
    subCategory: "jackets",
    rating: 4.7,
    reviews: 44,
    badge: "New",
    colors: ["#c9a96e", "#6b6960", "#1a1a2e"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4b4878?w=600",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600"
    ],
    description: "Sophisticated linen blazer with a modern tailored fit. Elevate any outfit from casual to smart-casual instantly.",
    details: ["100% Linen", "Tailored fit", "Two-button closure", "Chest pocket", "Dry clean recommended"],
    stock: 20,
    featured: false,
    newArrival: true,
  },
  {
    id: 8,
    name: "Gold Hoop Earrings Set",
    price: 1299,
    originalPrice: 1999,
    category: "accessories",
    subCategory: "jewelry",
    rating: 4.9,
    reviews: 415,
    badge: "Top Rated",
    colors: ["#c9a96e", "#c0c0c0"],
    sizes: ["One Size"],
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600"
    ],
    description: "Elegant 18k gold-plated hoop earrings set of 3 pairs. Lightweight, hypoallergenic, and perfect for daily wear.",
    details: ["18K Gold Plated", "Set of 3 pairs", "Hypoallergenic", "Lightweight design", "Tarnish resistant"],
    stock: 80,
    featured: false,
    newArrival: false,
  },
];

export default products;